apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "jx.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "jx.name" . }}
subjects:
- kind: ServiceAccount
{{- if .Values.serviceaccount.customName }}
  name: {{ .Values.serviceaccount.customName }}
{{- else }}
  name: {{ template "jx.fullname" . }}
{{- end }}
  namespace: {{ .Release.Namespace }}
