apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: chart
      timeout: 3h
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go-plugin/release.yaml@versionStream
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources: {}
        - name: release-binary
          resources: {}
        - name: build-and-push-image
          resources: {}
        - name: chart-docs
          resources: {}
        - name: changelog
          resources: {}
        - name: release-chart
          resources: {}
        - name: upload-binaries
          resources: {}
        - image: ghcr.io/jenkins-x/builder-go:latest
          name: promote-release
          resources: {}
          script: |
            #!/bin/bash
            source .jx/variables.sh
            ./promote.sh
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 3h
status: {}
